import { FormulaDefinition, DomainDefinition } from "./types";

// ─── DOMAIN DEFINITIONS ─────────────────────────────────────────────────────

export const DOMAIN_DEFINITIONS: DomainDefinition[] = [
  { id: "prenatal", label: "Prenatal & Global OB", color: "#1e40af", bg: "#eff6ff" },
  { id: "cervical", label: "Cervical Screening & Colposcopy", color: "#7c3aed", bg: "#f5f3ff" },
  { id: "surgery", label: "Surgical — Hysterectomy & MIS", color: "#be185d", bg: "#fdf2f8" },
  { id: "preventive", label: "Preventive & Well-Woman", color: "#047857", bg: "#f0fdf4" },
  { id: "labs", label: "Lab Utilization Patterns", color: "#b45309", bg: "#fffbeb" },
  { id: "em", label: "E/M & Billing Integrity", color: "#0e7490", bg: "#ecfeff" },
];

// ─── ALL HYSTERECTOMY CODES (used in multiple formulas) ──────────────────────

const OPEN_HYST_CODES = ["58150"];
const VAGINAL_HYST_CODES = ["58260", "58262", "58263", "58267", "58270", "58275", "58280"];
const MIS_HYST_CODES = ["58550", "58552", "58570", "58571", "58572", "58573"];
const ALL_HYST_CODES = [...OPEN_HYST_CODES, ...VAGINAL_HYST_CODES, ...MIS_HYST_CODES];

// Office visit codes used as population proxy for lab rate formulas
const OFFICE_VISIT_CODES = ["99202", "99203", "99204", "99205", "99211", "99212", "99213", "99214", "99215", "99395", "99396", "99397"];

// ─── FORMULA DEFINITIONS ────────────────────────────────────────────────────

export const FORMULA_DEFINITIONS: FormulaDefinition[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // DOMAIN: Prenatal & Global OB
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 59400: Global OB — Vaginal Delivery ---
  {
    id: "postpartum_visit_rate",
    label: "Postpartum Visit Rate",
    domainId: "prenatal",
    cptGroup: "59400",
    flag: "yellow",
    description: "COUNT(59430 or 99211–99215 with Z39.2 within 7–84d of delivery) / COUNT(59400) → Benchmark ≥ 0.90",
    note: "Rate < 0.75 = HEDIS PPC fail",
    computable: false,
    requiresPatientLevel: "Requires temporal relationship between delivery and postpartum visit dates per patient",
  },
  {
    id: "first_trimester_entry_rate",
    label: "First Trimester Entry Rate",
    domainId: "prenatal",
    cptGroup: "59400",
    flag: "yellow",
    description: "COUNT(first prenatal visit with EGA ≤ 13w6d) / COUNT(59400) → Benchmark ≥ 0.77",
    note: "Rate < 0.60 = potential late-entry pattern",
    computable: false,
    requiresPatientLevel: "Requires estimated gestational age (EGA) at first prenatal visit per patient",
  },
  {
    id: "antepartum_visit_adequacy",
    label: "Antepartum Visit Adequacy",
    domainId: "prenatal",
    cptGroup: "59400",
    flag: "red",
    description: "COUNT(59426 billed) / COUNT(59400) → Expected ≈ 1.00",
    note: "Ratio < 0.80: under-billing or skipped visits",
    computable: true,
    numeratorCodes: ["59426"],
    denominatorCodes: ["59400"],
    benchmark: 0.80,
    benchmarkOp: "gte",
  },
  {
    id: "global_ob_unbundling",
    label: "Global OB Unbundling Flag",
    domainId: "prenatal",
    cptGroup: "59400",
    flag: "red",
    description: "COUNT(59409 or 59410 same patient same date as 59400) > 0 → Flag ALL",
    note: "59409/59410 must not appear when 59400 billed same episode",
    computable: false,
    requiresPatientLevel: "Requires same-patient, same-date claim matching",
  },

  // --- 59514/59515: C-Section ---
  {
    id: "ntsv_csection_rate",
    label: "NTSV C-Section Rate",
    domainId: "prenatal",
    cptGroup: "59514 / 59515",
    flag: "red",
    description: "COUNT(59514+59515 with O82 + nulliparous flag) / COUNT(all singleton term vertex deliveries) → Benchmark < 0.236",
    note: "Rate > 0.30 = significant outlier",
    computable: false,
    requiresPatientLevel: "Requires nulliparity, singleton, term, and vertex presentation flags per delivery",
  },
  {
    id: "csection_vaginal_ratio",
    label: "C-Section to Vaginal Ratio",
    domainId: "prenatal",
    cptGroup: "59514 / 59515",
    flag: "yellow",
    description: "COUNT(59514+59515+59618+59620) / COUNT(59400+59409+59610+59612) → Benchmark < 0.40",
    note: "Ratio > 0.50 warrants chart review",
    computable: true,
    numeratorCodes: ["59514", "59515", "59618", "59620"],
    denominatorCodes: ["59400", "59409", "59610", "59612"],
    benchmark: 0.40,
    benchmarkOp: "lt",
  },
  {
    id: "early_elective_delivery",
    label: "Early Elective Delivery Flag (PC-01)",
    domainId: "prenatal",
    cptGroup: "59514 / 59515",
    flag: "red",
    description: "COUNT(delivery at 37w0d–38w6d AND no documented indication) → Target = 0",
    note: "Joint Commission reportable event",
    computable: false,
    requiresPatientLevel: "Requires gestational age at delivery and medical indication documentation",
  },
  {
    id: "tolac_rate",
    label: "TOLAC Rate",
    domainId: "prenatal",
    cptGroup: "59514 / 59515",
    flag: "yellow",
    description: "COUNT(59618+59620) / COUNT(patients with prior 59514) → Expected ≥ 0.20",
    note: "Rate < 0.10 may signal inadequate ACOG TOLAC counseling",
    computable: false,
    requiresPatientLevel: "Requires patient history of prior cesarean delivery",
  },

  // --- 59430: Postpartum Care Only ---
  {
    id: "postpartum_timing",
    label: "Postpartum Timing Compliance",
    domainId: "prenatal",
    cptGroup: "59430",
    flag: "yellow",
    description: "COUNT(59430 or E/M Z39.2 in [delivery+7d, delivery+84d]) / COUNT(deliveries) → Benchmark ≥ 0.90",
    note: "< 0.75 = HEDIS PPC fail",
    computable: false,
    requiresPatientLevel: "Requires delivery date and postpartum visit date per patient",
  },
  {
    id: "depression_screen_postpartum",
    label: "Depression Screen at Postpartum",
    domainId: "prenatal",
    cptGroup: "59430",
    flag: "yellow",
    description: "COUNT(96127 within 30d of 59430) / COUNT(59430) → Benchmark ≥ 0.85",
    note: "Absence = missed HEDIS PDS-E opportunity",
    computable: false,
    requiresPatientLevel: "Requires temporal linkage between screening and postpartum visit per patient",
  },

  // --- 82950/82951: Gestational Diabetes Screen ---
  {
    id: "gdm_screening_rate",
    label: "GDM Screening Rate",
    domainId: "prenatal",
    cptGroup: "82950 / 82951",
    flag: "yellow",
    description: "COUNT(82950+82951 at 24–28w) / COUNT(prenatal patients) → Benchmark ≥ 0.95",
    note: "Rate < 0.85 = workflow failure",
    computable: false,
    requiresPatientLevel: "Requires gestational age at time of test per patient",
  },
  {
    id: "gdm_rescreen",
    label: "GDM Post-Delivery Re-Screen",
    domainId: "prenatal",
    cptGroup: "82950 / 82951",
    flag: "red",
    description: "COUNT(82951 or 83036 at 4–12w postpartum) / COUNT(O24.4x patients) → Benchmark ≥ 0.90",
    note: "Well-known care gap and ACOG quality indicator",
    computable: false,
    requiresPatientLevel: "Requires GDM diagnosis and postpartum re-screening timing per patient",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOMAIN: Cervical Screening & Colposcopy
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 88141/88142/88175: Cervical Cytology ---
  {
    id: "ccs_screening_rate",
    label: "CCS Screening Rate",
    domainId: "cervical",
    cptGroup: "88141 / 88142 / 88175",
    flag: "yellow",
    description: "COUNT(patients 21–64 with Pap in 3yr window) / COUNT(eligible females 21–64) → Benchmark ≥ 0.75",
    note: "Rate < 0.65 = HEDIS underperformance",
    computable: false,
    requiresPatientLevel: "Requires patient age and screening date history per patient",
  },
  {
    id: "overscreening_under21",
    label: "Over-Screening < 21 Flag",
    domainId: "cervical",
    cptGroup: "88141 / 88142 / 88175",
    flag: "red",
    description: "COUNT(Pap where patient_age < 21) → Target = 0",
    note: "ACOG contraindicates screening < 21",
    computable: false,
    requiresPatientLevel: "Requires patient age at time of screening",
  },
  {
    id: "annual_pap_flag",
    label: "Annual Pap Flag (Over-Screening)",
    domainId: "cervical",
    cptGroup: "88141 / 88142 / 88175",
    flag: "red",
    description: "COUNT(patients with Pap 2 consecutive years, avg-risk, age 21–29) → Target = 0",
    note: "Violates ACOG q3yr guidance",
    computable: false,
    requiresPatientLevel: "Requires patient-level screening history across years",
  },
  {
    id: "pap_without_hpv_cotest",
    label: "Pap Without HPV Co-Test Age 30–65",
    domainId: "cervical",
    cptGroup: "88141 / 88142 / 88175",
    flag: "yellow",
    description: "COUNT(88141/88142 with NO 87624 same DOS, age 30–65) / COUNT(Paps age 30–65) → Benchmark < 0.20",
    note: "Co-testing preferred at 30–65",
    computable: false,
    requiresPatientLevel: "Requires same-date-of-service matching and patient age",
  },

  // --- 87624/87625: hrHPV Testing ---
  {
    id: "hpv_under25",
    label: "HPV Testing < 25 Flag",
    domainId: "cervical",
    cptGroup: "87624 / 87625",
    flag: "red",
    description: "COUNT(87624+87625 where age < 25 AND no abnormal cytology) → Target = 0",
    note: "Not recommended < 25",
    computable: false,
    requiresPatientLevel: "Requires patient age and prior cytology results",
  },
  {
    id: "genotyping_without_hrhpv",
    label: "87625 Without Prior 87624",
    domainId: "cervical",
    cptGroup: "87624 / 87625",
    flag: "red",
    description: "COUNT(87625 with NO 87624 within 90d) → Target = 0",
    note: "Genotyping only after confirmed hrHPV positive",
    computable: false,
    requiresPatientLevel: "Requires temporal ordering of HPV tests per patient",
  },

  // --- 57420/57421: Colposcopy ---
  {
    id: "colposcopy_timeliness",
    label: "Colposcopy Timeliness",
    domainId: "cervical",
    cptGroup: "57420 / 57421",
    flag: "yellow",
    description: "AVG(57420/57421 DOS − abnormal Pap DOS) → Benchmark ≤ 90 days",
    note: "Avg > 180 days for HSIL = serious quality failure",
    computable: false,
    requiresPatientLevel: "Requires dates of abnormal Pap and colposcopy per patient",
  },
  {
    id: "biopsy_rate_colposcopy",
    label: "Biopsy Rate at Colposcopy",
    domainId: "cervical",
    cptGroup: "57420 / 57421",
    flag: "yellow",
    description: "COUNT(57421) / COUNT(57420+57421) → Benchmark ≥ 0.85",
    note: "Low rate may indicate incomplete evaluation",
    computable: true,
    numeratorCodes: ["57421"],
    denominatorCodes: ["57420", "57421"],
    benchmark: 0.85,
    benchmarkOp: "gte",
  },
  {
    id: "colposcopy_without_abnormal",
    label: "Colposcopy Without Antecedent Abnormal",
    domainId: "cervical",
    cptGroup: "57420 / 57421",
    flag: "red",
    description: "COUNT(57420+57421 with NO R87.6xx in prior 12m) → Flag all",
    note: "Potential overutilization",
    computable: false,
    requiresPatientLevel: "Requires prior diagnosis codes per patient within 12-month window",
  },

  // --- 57461/57460: LEEP/LLETZ ---
  {
    id: "leep_rate_per_colposcopy",
    label: "LEEP Rate per Colposcopy",
    domainId: "cervical",
    cptGroup: "57461 / 57460",
    flag: "yellow",
    description: "COUNT(57461+57460) / COUNT(57420+57421) → Benchmark 0.20–0.40",
    note: "Rate > 0.50 = potential over-treatment",
    computable: true,
    numeratorCodes: ["57461", "57460"],
    denominatorCodes: ["57420", "57421"],
    benchmarkOp: "range",
    benchmarkRange: [0.20, 0.40],
  },
  {
    id: "leep_without_colposcopy",
    label: "LEEP Without Prior Colposcopy",
    domainId: "cervical",
    cptGroup: "57461 / 57460",
    flag: "red",
    description: "COUNT(57461+57460 with NO 57420+57421 in prior 6m) → Target = 0",
    note: "Skipping required diagnostic step",
    computable: false,
    requiresPatientLevel: "Requires temporal ordering of colposcopy and LEEP per patient",
  },
  {
    id: "leep_for_cin1",
    label: "LEEP for CIN1 Flag",
    domainId: "cervical",
    cptGroup: "57461 / 57460",
    flag: "red",
    description: "COUNT(57461+57460 where N87.0 AND no CIN2+ history) → Target = 0",
    note: "Immediate LEEP for CIN1 = overtreatment",
    computable: false,
    requiresPatientLevel: "Requires diagnosis codes and patient pathology history",
  },
  {
    id: "post_leep_followup",
    label: "Post-LEEP Follow-Up Compliance",
    domainId: "cervical",
    cptGroup: "57461 / 57460",
    flag: "yellow",
    description: "COUNT(87624 or 88142 at 4–6m post-57461) / COUNT(57461) → Benchmark ≥ 0.90",
    note: "Test-of-cure required per ASCCP",
    computable: false,
    requiresPatientLevel: "Requires temporal follow-up tracking per patient after LEEP",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOMAIN: Surgical — Hysterectomy & MIS
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 58150: Total Abdominal Hysterectomy ---
  {
    id: "open_hyst_rate",
    label: "Open Hysterectomy Rate (Benign)",
    domainId: "surgery",
    cptGroup: "58150",
    flag: "red",
    description: "COUNT(58150 where ICD-10 NOT C53–C57) / COUNT(all hysterectomy codes) → Benchmark < 0.15",
    note: "Rate > 0.25 = significant outlier. Note: computed from aggregate volumes (cannot filter by benign-only without diagnosis data).",
    computable: true,
    numeratorCodes: OPEN_HYST_CODES,
    denominatorCodes: ALL_HYST_CODES,
    benchmark: 0.15,
    benchmarkOp: "lt",
  },
  {
    id: "complication_proxy",
    label: "30-Day Complication Proxy",
    domainId: "surgery",
    cptGroup: "58150",
    flag: "yellow",
    description: "COUNT(99231–99233 or ED visit within 30d of 58150) / COUNT(58150) → Benchmark < 0.08",
    note: "Post-op inpatient or ED within 30d = complication proxy",
    computable: false,
    requiresPatientLevel: "Requires temporal linkage between surgery and post-op visits per patient",
  },
  {
    id: "return_to_or",
    label: "Unplanned Return to OR",
    domainId: "surgery",
    cptGroup: "58150",
    flag: "red",
    description: "COUNT(second OR procedure within 14d of 58150, same patient) / COUNT(58150) → Benchmark < 0.02",
    note: "Leapfrog/CMS patient safety indicator",
    computable: false,
    requiresPatientLevel: "Requires per-patient surgical procedure history within 14-day window",
  },

  // --- 58570-58573: Laparoscopic/Robotic Hysterectomy ---
  {
    id: "mis_hyst_rate",
    label: "MIS Hysterectomy Rate",
    domainId: "surgery",
    cptGroup: "58570 / 58571 / 58572 / 58573",
    flag: "yellow",
    description: "COUNT(58550+58552+58570+58571+58572+58573) / COUNT(all hysterectomy codes) → Benchmark ≥ 0.85",
    note: "Rate < 0.70 = red flag given robotic expertise",
    computable: true,
    numeratorCodes: MIS_HYST_CODES,
    denominatorCodes: ALL_HYST_CODES,
    benchmark: 0.85,
    benchmarkOp: "gte",
  },
  {
    id: "robotic_vs_lap",
    label: "Robotic vs. Laparoscopic Mix",
    domainId: "surgery",
    cptGroup: "58570 / 58571 / 58572 / 58573",
    flag: "yellow",
    description: "COUNT(58572+58573 with robotic facility code) / COUNT(all MIS hysterectomy) → Context-dependent",
    note: "High robotic rate (> 0.60) adds ~$3–5K/case — flag for cost analysis",
    computable: false,
    requiresPatientLevel: "Requires facility codes to distinguish robotic from standard laparoscopic",
  },
  {
    id: "concurrent_repair",
    label: "Concurrent Repair Without Indication",
    domainId: "surgery",
    cptGroup: "58570 / 58571 / 58572 / 58573",
    flag: "red",
    description: "COUNT(57240+51840 with 58570+ where NO N81.x or N39.3) → Flag all",
    note: "Prolapse repair without diagnosis = potential overutilization",
    computable: false,
    requiresPatientLevel: "Requires diagnosis codes to verify indication for concurrent repair",
  },
  {
    id: "opportunistic_salpingectomy",
    label: "Opportunistic Salpingectomy Rate",
    domainId: "surgery",
    cptGroup: "58570 / 58571 / 58572 / 58573",
    flag: "yellow",
    description: "COUNT(58661 or 58571 same DOS as hysterectomy) / COUNT(premenopausal hysterectomies) → Benchmark ≥ 0.70",
    note: "< 0.40 = missed cancer-prevention opportunity",
    computable: false,
    requiresPatientLevel: "Requires same-DOS matching and menopausal status per patient",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOMAIN: Preventive & Well-Woman
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 99395/99396/99397: Preventive Well-Woman ---
  {
    id: "annual_preventive_rate",
    label: "Annual Preventive Visit Rate",
    domainId: "preventive",
    cptGroup: "99395 / 99396 / 99397",
    flag: "yellow",
    description: "COUNT(unique patients with 99395+99396+99397) / COUNT(active female patients) → Benchmark ≥ 0.65",
    note: "Low rate may indicate scheduling gap or undercoding",
    computable: false,
    requiresPatientLevel: "Requires active patient panel denominator",
  },
  {
    id: "preventive_em_no_modifier",
    label: "Preventive + Problem E/M Without -25",
    domainId: "preventive",
    cptGroup: "99395 / 99396 / 99397",
    flag: "red",
    description: "COUNT(99395–99397 same DOS as 99213–99215 without -25 modifier) → Target = 0",
    note: "Missing modifier = billing error",
    computable: false,
    requiresPatientLevel: "Requires same-DOS matching and modifier data per claim",
  },
  {
    id: "age_code_mismatch",
    label: "Age Code Mismatch",
    domainId: "preventive",
    cptGroup: "99395 / 99396 / 99397",
    flag: "red",
    description: "COUNT(99395 where age > 39, 99396 where age < 40 or > 64, 99397 where age < 65) → Target = 0",
    note: "Auditable upcoding or clerical error",
    computable: false,
    requiresPatientLevel: "Requires patient age at time of service",
  },
  {
    id: "chlamydia_screen",
    label: "Chlamydia Screen at Preventive (HEDIS CHL)",
    domainId: "preventive",
    cptGroup: "99395 / 99396 / 99397",
    flag: "yellow",
    description: "COUNT(87491 within 30d of 99395, age 16–24) / COUNT(99395 age 16–24) → Benchmark ≥ 0.60",
    note: "HEDIS CHL care gap if low",
    computable: false,
    requiresPatientLevel: "Requires patient age and temporal matching between visit and lab",
  },

  // --- 96127: Depression Screening ---
  {
    id: "prenatal_depression_screen",
    label: "Prenatal Depression Screen Rate",
    domainId: "preventive",
    cptGroup: "96127",
    flag: "yellow",
    description: "COUNT(patients with 96127 in first two prenatal visits) / COUNT(prenatal patients) → Benchmark ≥ 0.85",
    note: "< 0.70 = HEDIS PND-E underperformance",
    computable: false,
    requiresPatientLevel: "Requires identification of prenatal visits and screening timing per patient",
  },
  {
    id: "postpartum_depression_screen",
    label: "Postpartum Depression Screen Rate",
    domainId: "preventive",
    cptGroup: "96127",
    flag: "yellow",
    description: "COUNT(96127 within 30d of postpartum visit) / COUNT(postpartum visits 7–84d) → Benchmark ≥ 0.85",
    note: "Highest-yield HEDIS gap for OB/GYN",
    computable: false,
    requiresPatientLevel: "Requires temporal linkage between screening and postpartum visit per patient",
  },
  {
    id: "positive_screen_followup",
    label: "Positive Screen Follow-Up Rate",
    domainId: "preventive",
    cptGroup: "96127",
    flag: "red",
    description: "COUNT(positive 96127 + 99484 or MH referral within 30d) / COUNT(positive screens) → Benchmark ≥ 0.80",
    note: "Positive screen without follow-up = ACOG CPG violation",
    computable: false,
    requiresPatientLevel: "Requires screening outcomes and follow-up tracking per patient",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOMAIN: Lab Utilization Patterns
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 84436/84439/84443: Thyroid Tests ---
  {
    id: "thyroid_test_rate",
    label: "Thyroid Test Rate per Office Visit",
    domainId: "labs",
    cptGroup: "84436 / 84439 / 84443",
    flag: "red",
    description: "COUNT(84436+84439+84443) / COUNT(office visits) → Flag if > 0.30 tests per visit",
    note: "Approximated using office visit volume as denominator. WebMD flags this as outlier for Dr. Lingenfelter.",
    computable: true,
    numeratorCodes: ["84436", "84439", "84443"],
    denominatorCodes: OFFICE_VISIT_CODES,
    benchmark: 0.30,
    benchmarkOp: "lt",
  },
  {
    id: "tsh_repeat_no_dx",
    label: "TSH Repeat Without Thyroid Diagnosis",
    domainId: "labs",
    cptGroup: "84436 / 84439 / 84443",
    flag: "red",
    description: "COUNT(84443 > 2x per patient per year with NO E00–E07) → Flag if > 15% of patients",
    note: "Potential overutilization; payer audit risk",
    computable: false,
    requiresPatientLevel: "Requires per-patient test frequency and thyroid diagnosis codes",
  },

  // --- 82306/82652: Vitamin D ---
  {
    id: "vitd_test_rate",
    label: "Vitamin D Test Rate per Office Visit",
    domainId: "labs",
    cptGroup: "82306 / 82652",
    flag: "red",
    description: "COUNT(82306+82652) / COUNT(office visits) → Flag if > 0.15 tests per visit",
    note: "Approximated using office visit volume as denominator. Routine screening NOT recommended by ACOG/USPSTF.",
    computable: true,
    numeratorCodes: ["82306", "82652"],
    denominatorCodes: OFFICE_VISIT_CODES,
    benchmark: 0.15,
    benchmarkOp: "lt",
  },
  {
    id: "vitd_annual_repeat",
    label: "Annual Repeat Without Deficiency Dx",
    domainId: "labs",
    cptGroup: "82306 / 82652",
    flag: "yellow",
    description: "COUNT(82306 in 2 consecutive years, same patient, no E55.x) → Benchmark < 0.20 of tested patients",
    note: "Reflexive ordering; CMS audit target",
    computable: false,
    requiresPatientLevel: "Requires multi-year per-patient test history and deficiency diagnosis",
  },

  // --- 81000/81003: Urinalysis ---
  {
    id: "urinalysis_per_visit",
    label: "Urinalysis Rate per Office Visit",
    domainId: "labs",
    cptGroup: "81000 / 81003",
    flag: "green",
    description: "COUNT(81000+81002+81003) / COUNT(office visits) → Expected 0.30–0.60 for OB/GYN",
    note: "Higher rates expected for OB practices (prenatal urinalysis ~1:1). Approximated using office visit denominator.",
    computable: true,
    numeratorCodes: ["81000", "81001", "81002", "81003"],
    denominatorCodes: OFFICE_VISIT_CODES,
    benchmarkOp: "range",
    benchmarkRange: [0.30, 0.60],
  },
  {
    id: "nonprenatal_urinalysis",
    label: "Non-Prenatal Urinalysis Rate",
    domainId: "labs",
    cptGroup: "81000 / 81003",
    flag: "yellow",
    description: "COUNT(81000+81003 for non-pregnant patients) / COUNT(non-pregnant visits) → Benchmark < 0.25",
    note: "High rate in non-prenatal patients warrants indication review",
    computable: false,
    requiresPatientLevel: "Requires pregnancy status per patient to separate prenatal from non-prenatal",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOMAIN: E/M & Billing Integrity
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 99213/99214/99215: Office E/M ---
  {
    id: "em_level_distribution",
    label: "E/M Level Distribution (% 99215)",
    domainId: "em",
    cptGroup: "99213 / 99214 / 99215",
    flag: "yellow",
    description: "COUNT(99215) / COUNT(99213+99214+99215) → CMS benchmark: 99215 < 0.25 for OB/GYN",
    note: "Rate > 0.35 = CMS audit trigger",
    computable: true,
    numeratorCodes: ["99215"],
    denominatorCodes: ["99213", "99214", "99215"],
    benchmark: 0.25,
    benchmarkOp: "lt",
  },
  {
    id: "em_high_complexity_no_indicators",
    label: "99215 Without High-Complexity Indicators",
    domainId: "em",
    cptGroup: "99213 / 99214 / 99215",
    flag: "red",
    description: "COUNT(99215 where NO complex ICD-10 AND < 40 min documented) → Flag if > 20% of 99215",
    note: "Post-2021 E/M: 99215 requires high MDM or ≥40 min total time",
    computable: false,
    requiresPatientLevel: "Requires diagnosis codes and documented time per 99215 encounter",
  },
  {
    id: "em_procedure_no_modifier",
    label: "E/M + Procedure Same Day Without -25",
    domainId: "em",
    cptGroup: "99213 / 99214 / 99215",
    flag: "red",
    description: "COUNT(99213–99215 same DOS as procedure CPT without modifier -25) → Target = 0",
    note: "Missing modifier = overpayment",
    computable: false,
    requiresPatientLevel: "Requires same-DOS matching and modifier data per claim",
  },
];
